;;; vimrc-mode.el --- Major mode for vimrc files

;; 2013 Andrew Pennebaker
;; URL: https://github.com/mcandre/vimrc-mode
;; Version: 0.3.1
;; Package-Requires: ()

;; Copyright (C) 2011 Alpha Tan
;;
;; Author: Alpha Tan <alphatan.zh@gmail.com>
;; Time-stamp: <2011-05-04 14:34:23>
;; Keywords: vimrc .vim
;; Homepage: vimrc-mode.sf.net

;;; Version Control:
;; $Rev::                                               $
;; $Author::                                            $
;; $Date::                                              $

;; This file is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation; either version 2, or (at your option)
;; any later version.

;; This file is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with GNU Emacs; see the file COPYING.  If not, write to
;; the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
;; Boston, MA 02111-1307, USA.

;;; Commentary:

;; Add the following to ~/.emacs:
;;
;;     (require 'vimrc-mode)
;;     (add-to-list 'auto-mode-alist '(".vim\\(rc\\)?$" . vimrc-mode))
;;

;;; Code:

(require 'font-lock)

(defcustom vimrc-mode-hook nil
  "Normal hook run when entering vimrc-mode."
  :type 'hook
  :group 'data)

;; Regexps
(defvar vimrc-font-lock-keywords
  `(
     ;; Comment start:
     ("\\(^\\|[\t ]\\)\\(\".*\\)$"
       (2 font-lock-comment-face)) ;; Comment end;

     ;; String start:
     ("\\(\"[^\n\r\"]*\"\\)\\|\\('[^\n\r]*'\\)"
       (0 font-lock-string-face)) ;; String end;

     ;; Function-name start:
     ("^[ \t]*\\(fun[ction]*[!]\\)[ \t]*\\([a-z:A-Z0-9_]+\\)?"
       (1 font-lock-keyword-face)
       (2 font-lock-function-name-face nil t)) ;; Function-name end;
     ("\\(\\([a-zA-Z]*:\\)?[a-zA-Z]*\\)("
       (1 font-lock-function-name-face nil t)) ;; Function-name end;

     ;; Variables start:
     ("\\(\\([avglbs]:\\)\\|\\([&$]\\)\\)\\([a-zA-Z][a-zA-Z0-9_]*\\)"
       (0 font-lock-variable-name-face)
       ) ;; Variables end;

     ;; Variables which can be prefixed with `no'
     (,(concat "[^_]\\<\\(\\(?:no\\)?"
               (regexp-opt '("autochdir" "acd"
                             "allowrevins" "ari"
                             "altkeymap" "akm"
                             "antialias" "anti"
                             "arabic" "arab"
                             "arabicshape" "arshape"
                             "autoindent" "ai"
                             "autoread" "ar"
                             "autowrite" "aw"
                             "autowriteall" "awa"
                             "backup" "bk"
                             "ballooneval" "beval"
                             "binary" "bin"
                             "bioskey" "biosk"
                             "bomb"
                             "buflisted" "bl"
                             "cindent" "cin"
                             "compatible" "cp"
                             "confirm" "cf"
                             "conskey" "consk"
                             "copyindent" "ci"
                             "cscopetag" "cst"
                             "cscopeverbose" "csverb"
                             "cursorbind" "crb"
                             "cursorcolumn" "cuc"
                             "cursorline" "cul"
                             "delcombine" "deco"
                             "diff"
                             "digraph" "dg"
                             "edcompatible" "ed"
                             "endofline" "eol"
                             "equalalways" "ea"
                             "errorbells" "eb"
                             "esckeys" "ek"
                             "expandtab" "et"
                             "exrc" "ex"
                             "fkmap" "fk"
                             "foldenable" "fen"
                             "gdefault" "gd"
                             "guipty"
                             "hidden" "hid"
                             "hkmap" "hk"
                             "hkmapp" "hkp"
                             "hlsearch" "hls"
                             "icon"
                             "ignorecase" "ic"
                             "imcmdline" "imc"
                             "imdisable" "imd"
                             "incsearch" "is"
                             "infercase" "inf"
                             "insertmode"  "im"
                             "joinspaces" "js"
                             "lazyredraw" "lz"
                             "linebreak" "lbr"
                             "lisp"
                             "list"
                             "loadplugins" "lpl"
                             "macatsui"
                             "magic"
                             "modeline" "ml"
                             "modifiable" "ma"
                             "modified" "mod"
                             "more"
                             "mousefocus" "mousef"
                             "mousehide" "mh"
                             "number" "nu"
                             "opendevice" "odev"
                             "paste"
                             "preserveindent" "pi"
                             "previewwindow" "pvw"
                             "prompt"
                             "readonly" "ro"
                             "relativenumber" "rnu"
                             "remap"
                             "restorescreen" "rs"
                             "revins" "ri"
                             "rightleft" "rl"
                             "ruler" "ru"
                             "scrollbind" "scb"
                             "secure"
                             "shellslash" "ssl"
                             "shelltemp" "stmp"
                             "shiftround" "sr"
                             "shortname" "sn"
                             "showcmd" "sc"
                             "showfulltag" "sft"
                             "showmatch" "sm"
                             "showmode" "smd"
                             "smartcase" "scs"
                             "smartindent" "si"
                             "smarttab" "sta"
                             "spell"
                             "splitbelow" "sb"
                             "splitright" "spr"
                             "startofline" "sol"
                             "swapfile" "swf"
                             "tagbsearch" "tbs"
                             "tagrelative" "tr"
                             "tagstack" "tgst"
                             "termbidi" "tbidi"
                             "terse"
                             "textauto" "ta"
                             "textmode" "tx"
                             "tildeop" "top"
                             "timeout" "to"
                             "title"
                             "ttimeout"
                             "ttybuiltin" "tbi"
                             "ttyfast" "tf"
                             "visualbell" "vb"
                             "warn"
                             "weirdinvert" "wiv"
                             "wildmenu" "wmnu"
                             "winfixheight" "wfh"
                             "winfixwidth" "wfw"
                             "wrap"
                             "wrapscan" "ws"
                             "write"
                             "writeany" "wa"
                             "writebackup" "wb"
                             ) t)
               "\\)\\>[^_]" )
      1 font-lock-variable-name-face)

     ;; The rest of the variables
     (,(concat "[^_]"
               (regexp-opt '("aleph" "al"
                             "ambiwidth" "ambw"
                             "arabicshape" "arshape"
                             "background" "bg"
                             "backspace" "bs"
                             "backupcopy" "bkc"
                             "backupdir" "bdir"
                             "backupext" "bex"
                             "backupskip" "bsk"
                             "balloondelay" "bdlay"
                             "balloonexpr" "bexpr"
                             "breakat" "brk"
                             "breakindent" "bri"
                             "breakindentopt" "briopt"
                             "browsedir" "bsdir"
                             "bufhidden" "bh"
                             "buftype" "bt"
                             "casemap" "cmp"
                             "cdpath" "cd"
                             "cedit"
                             "charconvert" "ccv"
                             "cinkeys" "cink"
                             "cinoptions" "cino"
                             "cinwords" "cinw"
                             "clipboard" "cb"
                             "cmdheight" "ch"
                             "cmdwinheight" "cwh"
                             "colorcolumn" "cc"
                             "columns" "co"
                             "comments" "com"
                             "commentstring" "cms"
                             "complete"
                             "completefunc" "cfu"
                             "completeopt" "cot"
                             "concealcursor" "cocu"
                             "conceallevel" "cole"
                             "cpoptions" "cpo"
                             "cryptmethod" "cm"
                             "cscopepathcomp" "cspc"
                             "cscopeprg" "csprg"
                             "cscopequickfix" "csqf"
                             "cscopetagorder" "csto"
                             "cscopeverbose" "csverb"
                             "debug"
                             "define" "def"
                             "dictionary" "dict"
                             "dex" "diffexpr"
                             "dip" "diffopt"
                             "directory" "dir"
                             "display" "dy"
                             "eadirection" "ead"
                             "encoding" "enc"
                             "equalprg" "ep"
                             "errorfile" "ef"
                             "errorformat" "efm"
                             "eventignore" "ei"
                             "fileencoding" "fenc"
                             "fe"
                             "fileencodings" "fencs"
                             "fileformat" "ff"
                             "fileformats" "ffs"
                             "filetype" "ft"
                             "fillchars" "fcs"
                             "fkmap" "fk"
                             "foldclose" "fcl"
                             "foldcolumn" "fdc"
                             "foldexpr" "fde"
                             "foldignore" "fdi"
                             "foldlevel" "fdl"
                             "foldlevelstart" "fdls"
                             "foldmarker" "fmr"
                             "foldmethod" "fdm"
                             "foldminlines" "fml"
                             "foldnestmax" "fdn"
                             "foldopen" "fdo"
                             "foldtext" "fdt"
                             "formatoptions" "fo"
                             "formatlistpat" "flp"
                             "formatprg" "fp"
                             "formatexpr" "fex"
                             "fsync" "fs"
                             "grepformat" "gfm"
                             "grepprg" "gp"
                             "guicursor" "gcr"
                             "guifont" "gfn"
                             "guifontset" "gfs"
                             "guifontwide" "gfw"
                             "guiheadroom" "ghr"
                             "guioptions" "go"
                             "guitablabel" "gtl"
                             "guitabtooltip" "gtt"
                             "helpfile" "hf"
                             "helpheight" "hh"
                             "helplang" "hlg"
                             "highlight" "hl"
                             "history" "hi"
                             "iconstring"
                             "imactivatefunc" "imaf"
                             "imactivatekey" "imak"
                             "iminsert" "imi"
                             "imsearch" "ims"
                             "imstatusfunc" "imsf"
                             "include" "inc"
                             "includeexpr" "inex"
                             "indentexpr" "inde"
                             "indentkeys" "indk"
                             "isfname" "isf"
                             "isident" "isi"
                             "iskeyword" "isk"
                             "isprint" "isp"
                             "key"
                             "keymap" "kmp"
                             "keymodel" "km"
                             "keywordprg" "kp"
                             "langmap" "lmap"
                             "langmenu" "lm"
                             "laststatus" "ls"
                             "lines"
                             "linespace" "lsp"
                             "lispwords" "lw"
                             "listchars" "lcs"
                             "makeef" "mef"
                             "makeprg" "mp"
                             "matchpairs" "mps"
                             "matchtime" "mat"
                             "maxcombine" "mco"
                             "maxfuncdepth" "mfd"
                             "maxmapdepth" "mmd"
                             "maxmem" "mm"
                             "maxmempattern" "mmp"
                             "maxmemtot" "mmt"
                             "menuitems" "mis"
                             "mkspellmem" "msm"
                             "modelines" "mls"
                             "mouse"
                             "mousemodel" "mousem"
                             "mouseshape" "mouses"
                             "mousetime" "mouset"
                             "mzquantum" "mzq"
                             "nrformats" "nf"
                             "numberwidth" "nuw"
                             "omnifunc" "ofu"
                             "operatorfunc" "opfunc"
                             "osfiletype" "oft"
                             "paragraphs" "para"
                             "pastetoggle" "pt"
                             "pex" "patchexpr"
                             "patchmode" "pm"
                             "path" "pa"
                             "previewheight" "pvh"
                             "printdevice" "pdev"
                             "printencoding" "penc"
                             "printexpr" "pexpr"
                             "printfont" "pfn"
                             "printheader" "pheader"
                             "printmbcharset" "pmbcs"
                             "printmbfont" "pmbfn"
                             "printoptions" "popt"
                             "pumheight" "ph"
                             "quoteescape" "qe"
                             "redrawtime" "rdt"
                             "regexpengine" "re"
                             "report"
                             "rightleftcmd" "rlc"
                             "rulerformat" "ruf"
                             "runtimepath" "rtp"
                             "scroll" "scr"
                             "scrolljump" "sj"
                             "scrolloff" "so"
                             "scrollopt" "sbo"
                             "sections" "sect"
                             "selection" "sel"
                             "selectmode" "slm"
                             "sessionoptions" "ssop"
                             "shell" "sh"
                             "shellcmdflag" "shcf"
                             "shellpipe" "sp"
                             "shellquote" "shq"
                             "shellredir" "srr"
                             "shelltype" "st"
                             "shellxescape" "sxe"
                             "shellxquote" "sxq"
                             "shiftwidth" "sw"
                             "shortmess" "shm"
                             "showbreak" "sbr"
                             "showtabline" "stal"
                             "sidescroll" "ss"
                             "sidescrolloff" "siso"
                             "softtabstop" "sts"
                             "spellcapcheck" "spc"
                             "spellfile" "spf"
                             "spelllang" "spl"
                             "spellsuggest" "sps"
                             "statusline" "stl"
                             "suffixes" "su"
                             "suffixesadd" "sua"
                             "swapsync" "sws"
                             "switchbuf" "swb"
                             "synmaxcol" "smc"
                             "syntax" "syn"
                             "tabline" "tal"
                             "tabpagemax" "tpm"
                             "tabstop" "ts"
                             "taglength" "tl"
                             "tags" "tag"
                             "term"
                             "termbidi" "tbidi"
                             "termencoding" "tenc"
                             "textwidth" "tw"
                             "thesaurus" "tsr"
                             "timeoutlen" "tm"
                             "ttimeoutlen" "ttm"
                             "titlelen"
                             "titleold"
                             "titlestring"
                             "toolbar" "tb"
                             "toolbariconsize" "tbis"
                             "ttymouse" "ttym"
                             "ttyscroll" "tsl"
                             "ttytype" "tty"
                             "undodir" "udir"
                             "undolevels" "ul"
                             "undoreload" "ur"
                             "updatecount" "uc"
                             "updatetime" "ut"
                             "verbose" "vbs"
                             "verbosefile" "vfile"
                             "viewdir" "vdir"
                             "viewoptions" "vop"
                             "viminfo" "vi"
                             "virtualedit" "ve"
                             "whichwrap" "ww"
                             "wildchar" "wc"
                             "wildcharm" "wcm"
                             "wildignore" "wig"
                             "wildmode" "wim"
                             "wildoptions" "wop"
                             "winaltkeys" "wak"
                             "window" "wi"
                             "winheight" "wh"
                             "winminheight" "wmh"
                             "winminwidth" "wmw"
                             "winwidth" "wiw"
                             "wrapmargin" "wm"
                             "wrapscan" "ws"
                             "writedelay" "wd"
                             ) 'words)
               "[^_]")
      1 font-lock-variable-name-face)

     ;; Keywords start:
     (,
     (concat "\\(^\\|[^_]\\)\\<\\("
                          "y[ank]*"
                    "\\|" "xnoreme"
                    "\\|" "xme"
                    "\\|" "xmapc[lear]*"
                    "\\|" "xa[ll]*"
                    "\\|" "X"
                    "\\|" "x[it]*"
                    "\\|" "wv[iminfo]*"
                    "\\|" "wundo"
                    "\\|" "ws[verb]*"
                    "\\|" "wqa[ll]*"
                    "\\|" "wq"
                    "\\|" "wp[revious]*"
                    "\\|" "wN[ext]*"
                    "\\|" "wn[ext]*"
                    "\\|" "winp[os]*"
                    "\\|" "windo"
                    "\\|" "winc[md]*"
                    "\\|" "win[size]*"
                    "\\|" "wh[ile]*"
                    "\\|" "wa[ll]*"
                    "\\|" "w[rite]*"
                    "\\|" "vs[plit]*"
                    "\\|" "vne[w]*"
                    "\\|" "vmapc[lear]*"
                    "\\|" "vimgrepa[dd]*"
                    "\\|" "vim[grep]*"
                    "\\|" "vie[w]*"
                    "\\|" "vi[sual]*"
                    "\\|" "vert[ical]*"
                    "\\|" "verb[ose]*"
                    "\\|" "ve[rsion]*"
                    "\\|" "up[date]*"
                    "\\|" "uns[ilent]*"
                    "\\|" "unlo[ckvar]*"
                    "\\|" "unh[ide]*"
                    "\\|" "undol[ist]*"
                    "\\|" "undoj[oin]*"
                    "\\|" "una[bbreviate]*"
                    "\\|" "u[ndo]*"
                    "\\|" "tu"
                    "\\|" "tu[nmenu]*"
                    "\\|" "ts[elect]*"
                    "\\|" "try"
                    "\\|" "tr[ewind]*"
                    "\\|" "tp[revious]*"
                    "\\|" "to[pleft]*"
                    "\\|" "tN[ext]*"
                    "\\|" "tn[ext]*"
                    "\\|" "tm"
                    "\\|" "tm[enu]*"
                    "\\|" "tl[ast]*"
                    "\\|" "tj[ump]*"
                    "\\|" "th[row]*"
                    "\\|" "tf[irst]*"
                    "\\|" "te[aroff]*"
                    "\\|" "tclf[ile]*"
                    "\\|" "tcld[o]*"
                    "\\|" "tc[l]*"
                    "\\|" "tags"
                    "\\|" "tabs"
                    "\\|" "tabr[ewind]*"
                    "\\|" "tabp[revious]*"
                    "\\|" "tabo[nly]*"
                    "\\|" "tabnew"
                    "\\|" "tabN[ext]*"
                    "\\|" "tabn[ext]*"
                    "\\|" "tabm[ove]*"
                    "\\|" "tabl[ast]*"
                    "\\|" "tabfir[st]*"
                    "\\|" "tabf[ind]*"
                    "\\|" "tabe[dit]*"
                    "\\|" "tabd[o]*"
                    "\\|" "tabc[lose]*"
                    "\\|" "tab"
                    "\\|" "ta[g]*"
                    "\\|" "t"
                    "\\|" "syncbind"
                    "\\|" "sv[iew]*"
                    "\\|" "sus[pend]*"
                    "\\|" "sunmenu"
                    "\\|" "sunme"
                    "\\|" "sun[hide]*"
                    "\\|" "sts[elect]*"
                    "\\|" "stopi[nsert]*"
                    "\\|" "stj[ump]*"
                    "\\|" "startr[eplace]*"
                    "\\|" "startg[replace]*"
                    "\\|" "star[tinsert]*"
                    "\\|" "sta[g]*"
                    "\\|" "st[op]*"
                    "\\|" "sre[wind]*"
                    "\\|" "spr[evious]*"
                    "\\|" "spellw[rong]*"
                    "\\|" "spellu[ndo]*"
                    "\\|" "spellr[epall]*"
                    "\\|" "spelli[nfo]*"
                    "\\|" "spelld[ump]*"
                    "\\|" "spe[llgood]*"
                    "\\|" "sp[lit]*"
                    "\\|" "sor[t]*"
                    "\\|" "so[urce]*"
                    "\\|" "snoremenu"
                    "\\|" "snoreme"
                    "\\|" "sno[magic]*"
                    "\\|" "sni[ff]*"
                    "\\|" "sN[ext]*"
                    "\\|" "sn[ext]*"
                    "\\|" "smenu"
                    "\\|" "sme"
                    "\\|" "sm[ap]*"
                    "\\|" "sm[agic]*"
                    "\\|" "sla[st]*"
                    "\\|" "sl[eep]*"
                    "\\|" "sim[alt]*"
                    "\\|" "sil[ent]*"
                    "\\|" "sign"
                    "\\|" "sh[ell]*"
                    "\\|" "sfir[st]*"
                    "\\|" "sf[ind]*"
                    "\\|" "setl[ocal]*"
                    "\\|" "setg[lobal]*"
                    "\\|" "setf[iletype]*"
                    "\\|" "se[t]*"
                    "\\|" "scripte[ncoding]*"
                    "\\|" "scrip[tnames]*"
                    "\\|" "sbr[ewind]*"
                    "\\|" "sbp[revious]*"
                    "\\|" "sbN[ext]*"
                    "\\|" "sbn[ext]*"
                    "\\|" "sbm[odified]*"
                    "\\|" "sbl[ast]*"
                    "\\|" "sbf[irst]*"
                    "\\|" "sba[ll]*"
                    "\\|" "sb[uffer]*"
                    "\\|" "sav[eas]*"
                    "\\|" "san[dbox]*"
                    "\\|" "sal[l]*"
                    "\\|" "sa[rgument]*"
                    "\\|" "rv[iminfo]*"
                    "\\|" "rundo"
                    "\\|" "rubyf[ile]*"
                    "\\|" "rubyd[o]*"
                    "\\|" "rub[y]*"
                    "\\|" "ru[ntime]*"
                    "\\|" "rightb[elow]*"
                    "\\|" "ri[ght]*"
                    "\\|" "rew[ind]*"
                    "\\|" "retu[rn]*"
                    "\\|" "ret[ab]*"
                    "\\|" "res[ize]*"
                    "\\|" "reg[isters]*"
                    "\\|" "redraws[tatus]*"
                    "\\|" "redr[aw]*"
                    "\\|" "redi[r]*"
                    "\\|" "red[o]*"
                    "\\|" "rec[over]*"
                    "\\|" "r[ead]*"
                    "\\|" "quita[ll]*"
                    "\\|" "qa[ll]*"
                    "\\|" "q[uit]*"
                    "\\|" "pyf[ile]*"
                    "\\|" "py[thon]*"
                    "\\|" "pw[d]*"
                    "\\|" "pu[t]*"
                    "\\|" "pts[elect]*"
                    "\\|" "ptr[ewind]*"
                    "\\|" "ptp[revious]*"
                    "\\|" "ptN[ext]*"
                    "\\|" "ptn[ext]*"
                    "\\|" "ptl[ast]*"
                    "\\|" "ptj[ump]*"
                    "\\|" "ptf[irst]*"
                    "\\|" "pta[g]*"
                    "\\|" "ps[earch]*"
                    "\\|" "promptr[epl]*"
                    "\\|" "promptf[ind]*"
                    "\\|" "profd[el]*"
                    "\\|" "prof[ile]*"
                    "\\|" "prev[ious]*"
                    "\\|" "pre[serve]*"
                    "\\|" "pp[op]*"
                    "\\|" "popu"
                    "\\|" "popu[p]*"
                    "\\|" "po[p]*"
                    "\\|" "perld[o]*"
                    "\\|" "ped[it]*"
                    "\\|" "pe[rl]*"
                    "\\|" "pc[lose]*"
                    "\\|" "P[rint]*"
                    "\\|" "p[rint]*"
                    "\\|" "opt[ions]*"
                    "\\|" "on[ly]*"
                    "\\|" "omapc[lear]*"
                    "\\|" "ol[dfiles]*"
                    "\\|" "o[pen]*"
                    "\\|" "nu[mber]*"
                    "\\|" "noh[lsearch]*"
                    "\\|" "nmapc[lear]*"
                    "\\|" "new"
                    "\\|" "nbs[tart]*"
                    "\\|" "nbc[lose]*"
                    "\\|" "nb[key]*"
                    "\\|" "N[ext]*"
                    "\\|" "n[ext]*"
                    "\\|" "mzf[ile]*"
                    "\\|" "mz[scheme]*"
                    "\\|" "mod[e]*"
                    "\\|" "mkvie[w]*"
                    "\\|" "mkv[imrc]*"
                    "\\|" "mksp[ell]*"
                    "\\|" "mks[ession]*"
                    "\\|" "mk[exrc]*"
                    "\\|" "menut[ranslate]*"
                    "\\|" "mat[ch]*"
                    "\\|" "marks"
                    "\\|" "mak[e]*"
                    "\\|" "ma[rk]*"
                    "\\|" "m[ove]*"
                    "\\|" "lw[indow]*"
                    "\\|" "lvimgrepa[dd]*"
                    "\\|" "lv[imgrep]*"
                    "\\|" "luafile"
                    "\\|" "luado"
                    "\\|" "lua"
                    "\\|" "lt[ag]*"
                    "\\|" "ls"
                    "\\|" "lr[ewind]*"
                    "\\|" "lpf[ile]*"
                    "\\|" "lp[revious]*"
                    "\\|" "lop[en]*"
                    "\\|" "lol[der]*"
                    "\\|" "lockv[ar]*"
                    "\\|" "loc[kmarks]*"
                    "\\|" "lo[adview]*"
                    "\\|" "lNf[ile]*"
                    "\\|" "lnf[ile]*"
                    "\\|" "lnew[er]*"
                    "\\|" "lne[xt]*"
                    "\\|" "lN[ext]*"
                    "\\|" "lmapc[lear]*"
                    "\\|" "lmak[e]*"
                    "\\|" "lli[st]*"
                    "\\|" "lla[st]*"
                    "\\|" "ll"
                    "\\|" "lgrepa[dd]*"
                    "\\|" "lgr[ep]*"
                    "\\|" "lgete[xpr]*"
                    "\\|" "lgetb[uffer]*"
                    "\\|" "lg[etfile]*"
                    "\\|" "lfir[st]*"
                    "\\|" "lf[ile]*"
                    "\\|" "lex[pr]*"
                    "\\|" "lefta[bove]*"
                    "\\|" "le[ft]*"
                    "\\|" "lcl[ose]*"
                    "\\|" "lch[dir]*"
                    "\\|" "lc[d]*"
                    "\\|" "lb[uffer]*"
                    "\\|" "later"
                    "\\|" "lan[guage]*"
                    "\\|" "laddf[ile]*"
                    "\\|" "laddb[uffer]*"
                    "\\|" "lad[dexpr]*"
                    "\\|" "la[st]*"
                    "\\|" "l[ist]*"
                    "\\|" "keepj[umps]*"
                    "\\|" "keepalt"
                    "\\|" "kee[pmarks]*"
                    "\\|" "k"
                    "\\|" "ju[mps]*"
                    "\\|" "j[oin]*"
                    "\\|" "iuna[bbrev]*"
                    "\\|" "isp[lit]*"
                    "\\|" "is[earch]*"
                    "\\|" "imapc[lear]*"
                    "\\|" "il[ist]*"
                    "\\|" "ij[ump]*"
                    "\\|" "if"
                    "\\|" "iabc[lear]*"
                    "\\|" "his[tory]*"
                    "\\|" "hid[e]*"
                    "\\|" "ha[rdcopy]*"
                    "\\|" "grepa[dd]*"
                    "\\|" "gr[ep]*"
                    "\\|" "go[to]*"
                    "\\|" "fu[nction]*"
                    "\\|" "for"
                    "\\|" "foldo[pen]*"
                    "\\|" "folddoc[losed]*"
                    "\\|" "foldd[oopen]*"
                    "\\|" "foldc[lose]*"
                    "\\|" "fo[ld]*"
                    "\\|" "fix[del]*"
                    "\\|" "fir[st]*"
                    "\\|" "fini[sh]*"
                    "\\|" "fina[lly]*"
                    "\\|" "fin[d]*"
                    "\\|" "filetype"
                    "\\|" "files"
                    "\\|" "f[ile]*"
                    "\\|" "exi[t]*"
                    "\\|" "exe[cute]*"
                    "\\|" "ex"
                    "\\|" "ene[w]*"
                    "\\|" "endw[hile]*"
                    "\\|" "endt[ry]*"
                    "\\|" "endfo[r]*"
                    "\\|" "endf[unction]*"
                    "\\|" "en[dif]*" 
                    "\\|" "emenu*"
                    "\\|" "em[enu]*"
                    "\\|" "elsei[f]*"
                    "\\|" "el[se]*"
                    "\\|" "echon"
                    "\\|" "echom[sg]*"
                    "\\|" "echoe[rr]*"
                    "\\|" "earlier"
                    "\\|" "e[dit]*"
                    "\\|" "dsp[lit]*"
                    "\\|" "ds[earch]*"
                    "\\|" "dr[op]*"
                    "\\|" "dl[ist]*"
                    "\\|" "dj[ump]*"
                    "\\|" "dig[raphs]*"
                    "\\|" "diffu[pdate]*"
                    "\\|" "diffthis"
                    "\\|" "diffsplit"
                    "\\|" "diffpu[t]*"
                    "\\|" "diffpatch"
                    "\\|" "diffoff"
                    "\\|" "diffg[et]*"
                    "\\|" "di[splay]*"
                    "\\|" "delm[arks]*"
                    "\\|" "delf[unction]*"
                    "\\|" "delc[ommand]*"
                    "\\|" "debugg[reedy]*"
                    "\\|" "d[elete]*"
                    "\\|" "cw[indow]*"
                    "\\|" "cuna[bbrev]*"
                    "\\|" "cr[ewind]*"
                    "\\|" "cq[uit]*"
                    "\\|" "cpf[ile]*"
                    "\\|" "cp[revious]*"
                    "\\|" "cope[n]*"
                    "\\|" "conf[irm]*"
                    "\\|" "con[tinue]*"
                    "\\|" "comp[iler]*"
                    "\\|" "comc[lear]*"
                    "\\|" "colo[rscheme]*"
                    "\\|" "col[der]*"
                    "\\|" "co[py]*"
                    "\\|" "cNf[ile]*"
                    "\\|" "cnf[ile]*"
                    "\\|" "cnew[er]*"
                    "\\|" "cN[ext]*"
                    "\\|" "cn[ext]*"
                    "\\|" "cmapc[lear]*"
                    "\\|" "clo[se]*"
                    "\\|" "cla[st]*"
                    "\\|" "cl[ist]*"
                    "\\|" "checkt[ime]*"
                    "\\|" "che[ckpath]*"
                    "\\|" "chd[ir]*"
                    "\\|" "changes"
                    "\\|" "cgete[xpr]*"
                    "\\|" "cgetb[uffer]*"
                    "\\|" "cg[etfile]*"
                    "\\|" "cfir[st]*"
                    "\\|" "cf[ile]*"
                    "\\|" "cex[pr]*"
                    "\\|" "ce[nter]*"
                    "\\|" "cd"
                    "\\|" "ccl[ose]*"
                    "\\|" "cc"
                    "\\|" "cb[uffer]*"
                    "\\|" "cat[ch]*"
                    "\\|" "cal[l]*"
                    "\\|" "caddf[ile]*"
                    "\\|" "caddb[uffer]*"
                    "\\|" "cad[dexpr]*"
                    "\\|" "cabc[lear]*"
                    "\\|" "c[hange]*"
                    "\\|" "bw[ipeout]*"
                    "\\|" "bun[load]*"
                    "\\|" "buffers"
                    "\\|" "bufdo"
                    "\\|" "bro[wse]*"
                    "\\|" "breakl[ist]*"
                    "\\|" "breakd[el]*"
                    "\\|" "breaka[dd]*"
                    "\\|" "brea[k]*"
                    "\\|" "br[ewind]*"
                    "\\|" "bp[revious]*"
                    "\\|" "bo[tright]*"
                    "\\|" "bN[ext]*"
                    "\\|" "bn[ext]*"
                    "\\|" "bm[odified]*"
                    "\\|" "bl[ast]*"
                    "\\|" "bf[irst]*"
                    "\\|" "bel[owright]*"
                    "\\|" "bd[elete]*"
                    "\\|" "bad[d]*"
                    "\\|" "ba[ll]*"
                    "\\|" "b[uffer]*"
                    "\\|" "aug[roup]*"
                    "\\|" "au[tocmd]*"
                    "\\|" "as[cii]*"
                    "\\|" "argu[ment]*"
                    "\\|" "argl[ocal]*"
                    "\\|" "argg[lobal]*"
                    "\\|" "arge[dit]*"
                    "\\|" "argdo"
                    "\\|" "argd[elete]*"
                    "\\|" "arga[dd]*"
                    "\\|" "ar[gs]*"
                    "\\|" "al[l]*"
                    "\\|" "abo[veleft]*"
                    "\\|" "abc[lear]*"
             "\\)\\>\\([^_]\\|$\\)"
             )
      ) ;; Keywords end; 

     ;; Builtins start:
     (,
      (concat "\\(^\\|[^_]\\)\\<\\("
                              "writefile"
                        "\\|" "winwidth"
                        "\\|" "winsaveview"
                        "\\|" "winrestview"
                        "\\|" "winrestcmd"
                        "\\|" "winnr"
                        "\\|" "winline"
                        "\\|" "winheight"
                        "\\|" "wincol"
                        "\\|" "winbufnr"
                        "\\|" "visualmode"
                        "\\|" "virtcol"
                        "\\|" "values"
                        "\\|" "undotree"
                        "\\|" "undofile"
                        "\\|" "type"
                        "\\|" "trunc"
                        "\\|" "tr"
                        "\\|" "toupper"
                        "\\|" "tolower"
                        "\\|" "tempname"
                        "\\|" "tanh"
                        "\\|" "tan"
                        "\\|" "taglist"
                        "\\|" "tagfiles"
                        "\\|" "tabpagewinnr"
                        "\\|" "tabpagenr"
                        "\\|" "tabpagebuflist"
                        "\\|" "system"
                        "\\|" "synstack"
                        "\\|" "synIDtrans"
                        "\\|" "synIDattr"
                        "\\|" "synID"
                        "\\|" "synconcealed"
                        "\\|" "substitute"
                        "\\|" "submatch"
                        "\\|" "strwidth"
                        "\\|" "strtrans"
                        "\\|" "strridx"
                        "\\|" "strpart"
                        "\\|" "strlen"
                        "\\|" "string"
                        "\\|" "stridx"
                        "\\|" "strftime"
                        "\\|" "strdisplaywidth"
                        "\\|" "strchars"
                        "\\|" "str2nr"
                        "\\|" "str2float"
                        "\\|" "sqrt"
                        "\\|" "split"
                        "\\|" "spellsuggest"
                        "\\|" "spellbadword"
                        "\\|" "soundfold"
                        "\\|" "sort"
                        "\\|" "sinh"
                        "\\|" "sin"
                        "\\|" "simplify"
                        "\\|" "shellescape"
                        "\\|" "setwinvar"
                        "\\|" "settabwinvar"
                        "\\|" "settabvar"
                        "\\|" "setreg"
                        "\\|" "setqflist"
                        "\\|" "setpos"
                        "\\|" "setmatches"
                        "\\|" "setloclist"
                        "\\|" "setline"
                        "\\|" "setcmdpos"
                        "\\|" "setbufvar"
                        "\\|" "serverlist"
                        "\\|" "server2client"
                        "\\|" "searchpos"
                        "\\|" "searchpairpos"
                        "\\|" "searchpair"
                        "\\|" "searchdecl"
                        "\\|" "search"
                        "\\|" "round"
                        "\\|" "reverse"
                        "\\|" "resolve"
                        "\\|" "repeat"
                        "\\|" "rename"
                        "\\|" "remove"
                        "\\|" "remote_send"
                        "\\|" "remote_read"
                        "\\|" "remote_peek"
                        "\\|" "remote_foreground"
                        "\\|" "remote_expr"
                        "\\|" "reltimestr"
                        "\\|" "reltime"
                        "\\|" "readfile"
                        "\\|" "range"
                        "\\|" "pumvisible"
                        "\\|" "printf"
                        "\\|" "prevnonblank"
                        "\\|" "pow"
                        "\\|" "pathshorten"
                        "\\|" "nr2char"
                        "\\|" "nextnonblank"
                        "\\|" "mzeval"
                        "\\|" "mode"
                        "\\|" "mkdir"
                        "\\|" "min"
                        "\\|" "max"
                        "\\|" "matchstr"
                        "\\|" "matchlist" 
                        "\\|" "matchend"
                        "\\|" "matchdelete"
                        "\\|" "matcharg"
                        "\\|" "matchadd"
                        "\\|" "match"
                        "\\|" "mapcheck"
                        "\\|" "maparg"
                        "\\|" "map"
                        "\\|" "log10"
                        "\\|" "log"
                        "\\|" "localtime"
                        "\\|" "lispindent"
                        "\\|" "line2byte"
                        "\\|" "line"
                        "\\|" "libcallnr"
                        "\\|" "libcall"
                        "\\|" "len"
                        "\\|" "keys"
                        "\\|" "join"
                        "\\|" "items"
                        "\\|" "islocked"
                        "\\|" "isdirectory"
                        "\\|" "insert"
                        "\\|" "inputsecret"
                        "\\|" "inputsave"
                        "\\|" "inputrestore"
                        "\\|" "inputlist"
                        "\\|" "inputdialog"
                        "\\|" "input"
                        "\\|" "index"
                        "\\|" "indent"
                        "\\|" "iconv"
                        "\\|" "hostname"
                        "\\|" "hlID"
                        "\\|" "hlexists"
                        "\\|" "histnr"
                        "\\|" "histget"
                        "\\|" "histdel"
                        "\\|" "histadd"
                        "\\|" "hasmapto"
                        "\\|" "haslocaldir"
                        "\\|" "has_key"
                        "\\|" "has"
                        "\\|" "globpath"
                        "\\|" "glob"
                        "\\|" "getwinvar"
                        "\\|" "getwinposy"
                        "\\|" "getwinposx"
                        "\\|" "gettabwinvar"
                        "\\|" "gettabvar"
                        "\\|" "getregtype"
                        "\\|" "getreg"
                        "\\|" "getqflist"
                        "\\|" "getpos"
                        "\\|" "getpid"
                        "\\|" "getmatches"
                        "\\|" "getloclist"
                        "\\|" "getline"
                        "\\|" "getftype"
                        "\\|" "getftime"
                        "\\|" "getfsize"
                        "\\|" "getfperm"
                        "\\|" "getfontname"
                        "\\|" "getcwd"
                        "\\|" "getcmdtype"
                        "\\|" "getcmdpos"
                        "\\|" "getcmdline"
                        "\\|" "getcharmod"
                        "\\|" "getchar"
                        "\\|" "getbufvar"
                        "\\|" "getbufline"
                        "\\|" "get"
                        "\\|" "garbagecollect"
                        "\\|" "function"
                        "\\|" "foreground"
                        "\\|" "foldtextresult"
                        "\\|" "foldtext"
                        "\\|" "foldlevel"
                        "\\|" "foldclosedend"
                        "\\|" "foldclosed"
                        "\\|" "fnamemodify"
                        "\\|" "fnameescape"
                        "\\|" "fmod"
                        "\\|" "floor"
                        "\\|" "float2nr"
                        "\\|" "findfile"
                        "\\|" "finddir"
                        "\\|" "filter"
                        "\\|" "filewritable"
                        "\\|" "filereadable"
                        "\\|" "feedkeys"
                        "\\|" "extend"
                        "\\|" "expr8"
                        "\\|" "expand"
                        "\\|" "exp"
                        "\\|" "exists"
                        "\\|" "eventhandler"
                        "\\|" "eval"
                        "\\|" "escape"
                        "\\|" "empty"
                        "\\|" "diff_hlID"
                        "\\|" "diff_filler"
                        "\\|" "did_filetype"
                        "\\|" "delete"
                        "\\|" "deepcopy"
                        "\\|" "cursor"
                        "\\|" "cscope_connection"
                        "\\|" "count"
                        "\\|" "cosh"
                        "\\|" "cos"
                        "\\|" "copy"
                        "\\|" "contained"
                        "\\|" "confirm"
                        "\\|" "complete_check"
                        "\\|" "complete_add"
                        "\\|" "complete"
                        "\\|" "col"
                        "\\|" "clearmatches"
                        "\\|" "cindent"
                        "\\|" "char2nr"
                        "\\|" "changenr"
                        "\\|" "ceil"
                        "\\|" "call"
                        "\\|" "byteidx"
                        "\\|" "byte2line"
                        "\\|" "bufwinnr"
                        "\\|" "bufnr"
                        "\\|" "bufname"
                        "\\|" "bufloaded"
                        "\\|" "buflisted"
                        "\\|" "bufexists"
                        "\\|" "browsedir"
                        "\\|" "browse"
                        "\\|" "atan2"
                        "\\|" "atan"
                        "\\|" "asin"
                        "\\|" "argv"
                        "\\|" "argidx"
                        "\\|" "argc"
                        "\\|" "append"
                        "\\|" "add"
                        "\\|" "acos"
                        "\\|" "abs"
             "\\)\\>\\([^_]\\|$\\)")
      2 font-lock-builtin-face) ;; Builtins end;

     ;;
     ;; Operators start:
     (,(concat "\\("
                       ;; word char
                             "\\(\\<isnot\\>\\)"
                       "\\|" "\\(\\<is\\>\\)"

                       "\\|" "\\(![=~]?[#?]?\\)"
                       "\\|" "\\(>[#\\\\?=]?[#?]?\\)"
                       "\\|" "\\(<[#\\\\?=]?[#?]?\\)" 
                       "\\|" "\\(\\+=?\\)"
                       "\\|" "\\(-=?\\)"
                       "\\|" "\\(=[=~]?[#?]?\\)"
                       "\\|" "\\(||\\)"
                       "\\|" "\\(&&\\)"

                       "\\|" "\\(\\.\\)"
                   "\\)"
                   )
           1 font-lock-constant-face) ;; Operators end;
     )
 "Default expressions to highlight in Vimrc mode.")

;;;###autoload (add-to-list 'auto-mode-alist '("\\.vim\\'" . vimrc-mode))
;;;###autoload (add-to-list 'auto-mode-alist '("[._]?g?vimrc\\'" . vimrc-mode))
;;;###autoload (add-to-list 'auto-mode-alist '("\\.exrc\\'" . vimrc-mode))

(defalias 'vimrc--parent-mode
  (if (fboundp 'prog-mode) #'prog-mode #'fundamental-mode))

;;;###autoload
(define-derived-mode vimrc-mode vimrc--parent-mode "Vimrc"
  "Major mode for editing `vimrc', `xxx.vim' and `.exrc' configuration files."
  (setq font-lock-defaults '(vimrc-font-lock-keywords))
  (set (make-local-variable 'comment-start) "\"")
  (set (make-local-variable 'comment-end) "")
  (modify-syntax-entry ?\" ".")
  ;(set (make-local-variable 'comment-start-skip) "\"\\* +")
  (run-hooks 'vimrc-mode-hook))

(provide 'vimrc-mode)

;;; vimrc-mode.el ends here
